### PR TITLE
feat: add withRouter and withStore HOCs and refactor Link and RouterL…

### PR DESCRIPTION
**Pull request by kutuluk**
…ink components

### CODE REVIEW

**Comment by kutuluk** [comment]
#23

**Comment by kutuluk** [comment]
Do you have any questions about this PR?

**Comment by nareshbhatia** [comment]
No questions yet. Just too busy at work. I will try to look at it this weekend.

**Comment by kutuluk** [comment]
This PR is not sufficiently developed. Next week I will present a new version in accordance with https://cdb.reacttraining.com/use-a-render-prop-50de598f11ce

**Pull request closed without merging**
